### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jano23** [DiegoAz/Theme-Autumn#1]
Give us different dot color options.

Love this  theme!!

**Comment by DiegoAz** [comment]
Hi @jano23, Glad you like it. :)

It is not possible to set options to Color Schemes. So you have to create a folder in the Packages folder with a tmTheme file, for example Mythemes\AutumnModified.tmTheme and make the changes you want to. 

Here you can read info about color schemes http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/reference/color_schemes.html 

Yo can use the plugin ScopeHunter to know the scopes. https://packagecontrol.io/packages/ScopeHunter

**Comment by jano23** [comment]
Diego,
Is options for the Theme different than options for the Color Schemes? I have seen some themes that have color options for the folder icons. They are set in the Settings - User > Preferences.sublime-settings file. I was probably using the wrong word(s). I love the round green dots that signify the folders. With a black dot when they are open.

**Comment by DiegoAz** [comment]
I thought you were talking about the color scheme punctuation. OK, I will add other "folder" colors soon.

**Comment by jano23** [comment]
Awesome

**Comment by DiegoAz** [comment]
I am sorry for the delay. v1.3.0 offers 2 more options: 
"theme-autumn-gray-folders" and "theme-autumn-orange-folders"
