### ISSUE TITLE
Broken in ST3

### ISSUE THREAD

**Issue by TheJaredWilcurt** [DiegoAz/Theme-Autumn#3]
ST3 release just went out, it broke this theme

**Comment by DiegoAz** [comment]
Hi, I updated the readme with a Note about Sublime Text 3 (Build 3143). Can you tell me it works for you?

**Comment by TheJaredWilcurt** [comment]
Yeah, that's pretty dumb though that they aren't just shipping the default theme anymore to fix all the broken themes.

You should update the docs to be easier to understand, like this:

* * *

Because this theme was referencing images in the Theme - Default that no longer exist you need to download this file and unzip the folder into the Sublime packages directory.

* **[Theme Default.zip](https://github.com/DiegoAz/Theme-Autumn/raw/master/Theme%20-%20Default.zip)**
* Sublime Text 3\Data\Packages\Theme - Default\Default.sublime-theme

Zip file contains the `Theme - Default` from before build 3143. **[More info](https://forum.sublimetext.com/t/very-colorful-tabs/31244)**.

* * *

```
Because this theme was referencing images in the Theme - Default that no longer exist you need to download this file and unzip the folder into the Sublime packages directory.

* **[Theme Default.zip](https://github.com/DiegoAz/Theme-Autumn/raw/master/Theme%20-%20Default.zip)**
* Sublime Text 3\Data\Packages\Theme - Default\Default.sublime-theme

Zip file contains the `Theme - Default` from before build 3143. **[More info](https://forum.sublimetext.com/t/very-colorful-tabs/31244)**.
```

**Comment by DiegoAz** [comment]
I update the theme to include the Theme - Default inside and avoid downloading the .zip file. Visit https://github.com/DiegoAz/Theme-Autumn.
